# Generated by Django 6.0.3 on 2026-03-15 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('GIFT_CARD', 'Gift Card Asset')], max_length=20)),
                ('card_details', models.TextField(blank=True, help_text='Enter Gift Card Code/PIN here', null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Success'), ('FAILED', 'Declined')], default='PENDING', max_length=20)),
                ('is_credited', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('settlement_address', models.CharField(blank=True, max_length=255, null=True)),
                ('last_roi_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='SSN/Tax ID')),
                ('id_type', models.CharField(choices=[('DL', 'Drivers License'), ('PP', 'Passport'), ('ID', 'National ID')], default='DL', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('UNSUBMITTED', 'Unsubmitted'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNSUBMITTED', max_length=20)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='kyc_docs/%Y/%m/%d/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='kyc_docs/%Y/%m/%d/')),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_roi_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('category', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal Issue'), ('DEPOSIT', 'Deposit Issue'), ('KYC', 'Identity Verification'), ('ACCOUNT', 'Account Settings'), ('OTHER', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending Admin'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('address', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(blank=True, help_text='Paste the blockchain TXID or payment reference here', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_refunded', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PROFIT', 'Profit'), ('BONUS', 'Bonus')], max_length=20)),
                ('gateway', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('GIFTCARD', 'Giftcard'), ('INTERNAL', 'Internal Transfer')], default='INTERNAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('crypto_currency', models.CharField(blank=True, help_text='e.g., BTC, USDT, ETH', max_length=10, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain TXID', max_length=255, null=True)),
                ('card_type', models.CharField(blank=True, help_text='e.g., Amazon, Apple', max_length=50, null=True)),
                ('card_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal feedback for the user', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['reference_id'], name='core_transa_referen_da0157_idx'), models.Index(fields=['user'], name='core_transa_user_id_c94326_idx')],
            },
        ),
    ]
